export const REQUEST_BUSINESSLIST = 'REQUEST_BUSINESSLIST';  
export const ERROR_BUSINESSLIST = 'ERROR_BUSINESSLIST';  
export const RECEIVE_BUSINESSLIST = 'RECEIVE_BUSINESSLIST';  

export const SELECT_BUSINESS = 'SELECT_BUSINESS';  
export const FAV_BUSINESS = 'FAV_BUSINESS';  

export const START_FETCHING = 'START_FETCHING';
export const FINISHED_FETCHING = 'FINISHED_FETCHING';

export const SEND_MESSAGE = 'SEND_MESSAGE';

export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';
export const RECEIVE_MESSAGES_ONBOARDING = 'RECEIVE_MESSAGES_ONBOARDING';
export const ADD_USER_MESSAGE = 'ADD_USER_MESSAGE';

export const STARTED_WRITING = 'STARTED_WRITING';
export const FINISHED_WRITING = 'FINISHED_WRITING';

export const AUTH_USER = 'AUTH_USER';

export const RECEIVE_CONVERSATIONS = 'RECEIVE_CONVERSATIONS';